### ISSUE TITLE
chore: fix evidence initialize

### ISSUE THREAD

**Issue by matsonj** [MeltanoLabs/evidence-ext#38]
getting an error when running ```meltano invoke evidence initialize```. Will look into once evidence v 0.17 is running.

**Comment by matsonj** [comment]
ah I can't assign it to myself, but happy to fix on my fork.

**Comment by edgarrmondragon** [comment]
> ah I can't assign it to myself, but happy to fix on my fork.

Thanks @matsonj, just assigned to you 😄

**Comment by matsonj** [comment]
Ok going to pick this up when Evidence ships the next update to accommodate duckdb 0.8.1 which means we can also sneak motherduck support in too.

**Comment by edgarrmondragon** [comment]
Blocked by https://github.com/motherduckdb/duckdb-async/pull/11

**Comment by archiewood** [comment]
https://github.com/evidence-dev/evidence/pull/1030

**Comment by matsonj** [comment]
Just did some testing, no longer getting an error on this but the sample project here is more up to date than ```evidence-dev/template#HEAD``` which is fine.
